title: files_photo-gallery
author:
  name: ZHENG Robert
  #email: no.spam@hotmail.dev
description: QT6 CXX20 console app to convert photos and add Metadata to Database

remote_theme: jekyll/minima
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto
  social_links: 
    - { platform: github,         user_url: "https://github.com/jekyll/minima" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  date_format: "%Y-%m-%d %H:%M"


author:
  name: ZHENG Robert
  #email: no.spam@hotmail.dev

page_created: 2024-09-09
page_url: https://zheng-bote.github.io/qt_files_photo-gallery
page_desc: QT6 CXX20 console app to convert photos and add Metadata to Database

header_pages:
  - about.md
  - links.md
