theme: minima

minima:
  skin: solarized-light

author:
  name: ZHENG Robert
  #email: no.spam@hotmail.dev

page_created: 2024-09-09
page_url: https://zheng-bote.github.io/qt_files_photo-gallery
page_desc: QT6 CXX20 console app to convert photos and add Metadata to Database

header_pages:
  - about.md
  - links.md
